classDiagram
    class User {
        - id: String
        - email: String
        - firstName: String
        - lastName: String
        - phone: String
        - role: UserRole
        - passwordHash: String
        - isActive: Boolean
        - avatarUrl: String
        - createdAt: DateTime
        - updatedAt: DateTime
    }

    class Address {
        - id: String
        - userId: String
        - label: String
        - street: String
        - city: String
        - zipCode: String
        - country: String
        - isDefault: Boolean
        - createdAt: DateTime
    }

    class RefreshToken {
        - id: String
        - userId: String
        - token: String
        - expiresAt: DateTime
        - createdAt: DateTime
    }

    class ContactMessage {
        - id: String
        - name: String
        - email: String
        - subject: String
        - message: String
        - createdAt: DateTime
    }

    class UserRole {
        <<enumeration>>
        ADMIN
        CLIENT
    }

    User "1" --> "*" Address : Posseder
    User "1" --> "*" RefreshToken : Avoir
    User --> UserRole : Avoir
